# version: "2.19.1"
# services:
#   backend:
#     build: ./ecommerce/
#     ports:
#       - "8080:8080"
#     depends_on:
#       - "db"
#     links:
#       - db
#     environment:
#       SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ecommerce
#       SPRING_DATASOURCE_USERNAME: root
#       SPRING_DATASOURCE_PASSWORD: 145236987Ben!
#     healthcheck:
#       test:
#         [
#           "CMD-SHELL",
#           "curl --fail http://localhost:8080/actuator/health || exit 1",
#         ]
#       interval: 30s
#       timeout: 10s
#       retries: 5
#   frontend:
#     build: ./ecommerce-UI/react-app/
#     environment:
#       VITE_API_URL: http://localhost:8080
#     ports:
#       - "5173:5173"
#     depends_on:
#       - "backend"
#     links:
#       - backend
#   db:
#     image: mysql:8.0.33
#     environment:
#       MYSQL_ROOT_PASSWORD: 145236987Ben!
#       MYSQL_ROOT_USER: root
#       MYSQL_DATABASE: ecommerce
#     ports:
#       - "3309:3306"
#     volumes:
#       - db-data:/var/lib/mysql
#     healthcheck:
#       test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 --silent"]
#       timeout: 5s
#       retries: 10
# volumes:
#   db-data:

version: "2.19.1"

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
  backend:
    build: ./ecommerce/
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ecommerce
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 145236987Ben!
    expose:
      - 8080
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://localhost:8080/actuator/health || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
  frontend:
    build: ./ecommerce-UI/react-app/
    environment:
      VITE_API_URL: http://localhost
    ports:
      - "5173:5173"
    expose:
      - 5173
  db:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: 145236987Ben!
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: ecommerce
    ports:
      - "3309:3306"
    volumes:
      - db-data:/var/lib/mysql
 
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 --silent"]
      timeout: 5s
      retries: 10
volumes:
  db-data:
