version: "2.19.1"

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build: ./ecommerce/
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ecommerce
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 145236987Ben!
    expose:
      - 8080
  db:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: 145236987Ben!
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: ecommerce
    ports:
      - "3309:3306"
    volumes:
      - db-data:/var/lib/mysql
 
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 --silent"]
      timeout: 5s
      retries: 10
volumes:
  db-data:
