version: "2.19.1"
services:
  backend:
    build: ./ecommerce/
    ports:
      - "10.7.148.183:8080:8080"
    depends_on:
      - "db"
    links:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ecommerce
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 145236987Ben!
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://localhost:8080/actuator/health || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
  frontend:
    build: ./ecommerce-UI/react-app/
    environment:
      VITE_API_URL: http://10.7.148.183:8080
    ports:
      - "10.7.148.183:5173:5173"
    depends_on:
      - "backend"
    links:
      - backend
  db:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: 145236987Ben!
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: ecommerce
    ports:
      - "3309:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 --silent"]
      timeout: 5s
      retries: 10
volumes:
  db-data:



# version: "2.19.1"
# services:
#   backend:
#     build: ./ecommerce/
#     environment:
#       SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ecommerce
#       SPRING_DATASOURCE_USERNAME: root
#       SPRING_DATASOURCE_PASSWORD: 145236987Ben!
#     healthcheck:
#       test:
#         [
#           "CMD-SHELL",
#           "curl --fail http://localhost:8080/actuator/health || exit 1",
#         ]
#       interval: 30s
#       timeout: 10s
#       retries: 5
#   frontend:
#     build: ./ecommerce-UI/react-app/
#     environment:
#       VITE_API_URL: http://backend:8080
#   db:
#     image: mysql:8.0.33
#     environment:
#       MYSQL_ROOT_PASSWORD: 145236987Ben!
#       MYSQL_ROOT_USER: root
#       MYSQL_DATABASE: ecommerce
#     volumes:
#       - db-data:/var/lib/mysql
#     healthcheck:
#       test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 --silent"]
#       timeout: 5s
#       retries: 10
#   nginx:
#     image: nginx
#     ports:
#       - "80:80"
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf:ro
#     depends_on:
#       - frontend
#       - backend
# volumes:
#   db-data: