export const API_USER = "http://localhost:8080/api/v1/users/"
export const API_CATEGORY = "http://localhost:8080/api/v1/categories/"
export const API_PRODUCT = "http://localhost:8080/api/v1/products/"
export const API_CART = "http://localhost:8080/api/v1/carts/"
export const API_PAYMENT = "http://localhost:8080/api/v1/payment/"