export const USER_INSERT = "USER_INSERT"
export const USER_CLEAR_STATE = "USER_CLEAR_STATE"
export const USER_GET_BY_USERNAME = "USER_GET_BY_USERNAME"




export const COMMON_ERROR_SET = 'COMMON_ERROR_SET'
export const COMMON_MESSAGE_SET = 'COMMON_MESSAGE_SET'
export const COMMON_LOADING_SET = 'COMMON_LOADING_SET'