export const USER_INSERT = "USER_INSERT"
export const USER_CLEAR_STATE = "USER_CLEAR_STATE"
export const USER_GET_BY_USERNAME = "USER_GET_BY_USERNAME"




export const COMMON_ERROR_SET = 'COMMON_ERROR_SET'
export const COMMON_MESSAGE_SET = 'COMMON_MESSAGE_SET'
export const COMMON_LOADING_SET = 'COMMON_LOADING_SET'


export const CATEGORY_INSERT = "CATEGORY_INSERT"
export const CATEGORIES_GET_ALL = "CATEGORIES_GET_ALL"
export const CATEGORIES_GET_ALL_ACTIVE = "CATEGORIES_GET_ALL_ACTIVE"
export const CATEGORIES_GET_ALL_INACTIVE = "CATEGORIES_GET_ALL_INACTIVE"
export const CATEGORY_SET = "CATEGORY_SET"
export const CATEGORY_CLEAR_STATE = "CATEGORY_CLEAR_STATE"
export const CATEGORY_UPDATE = "CATEGORY_UPDATE"
export const CATEGORY_DELETE = "CATEGORY_DELETE"


export const PRODUCT_INSERT = "PRODUCT_INSERT"
export const PRODUCTS_GET_ALL = "PRODUCTS_GET_ALL"
export const PRODUCTS_GET_ALL_ACTIVE = "PRODUCTS_GET_ALL_ACTIVE"
export const PRODUCTS_GET_ALL_INACTIVE = "PRODUCTS_GET_ALL_INACTIVE"
export const PRODUCT_CLEAR_STATE = "PRODUCT_CLEAR_STATE"
export const PRODUCT_SET = "PRODUCT_SET"
export const PRODUCT_UPDATE = "PRODUCT_UPDATE"
export const PRODUCT_DELETE = "PRODUCT_DELETE"


export const CART_SET = "CART_SET"
export const CART_INSERT = "CART_INSERT"
export const CART_GET_ALL = "CART_GET_ALL"
export const CART_CLEAR_STATE = "CART_CLEAR_STATE"
export const CART_DELETE_PRODUCT = "CART_DELETE_PRODUCT"

export const PAYMENT_INSERT_ORDER_INFO ="PAYMENT_INSERT_ORDER_INFO"
export const PAYMENT_GET_ORDER_INFO_USER ="PAYMENT_GET_ORDER_INFO_USER"
export const PAYMENT_CLEAR_CARTS ="PAYMENT_CLEAR_CARTS"
export const PAYMENT_SET_CARTS ="PAYMENT_SET_CARTS"
export const PAYMENT_CLEAR_STATE ="PAYMENT_CLEAR_STATE"
export const PAYMENT_SET_STATUS ="PAYMENT_SET_STATUS"